# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialogAbout(object):
    def setupUi(self, dialogAbout):
        dialogAbout.setObjectName("dialogAbout")
        dialogAbout.resize(558, 347)
        dialogAbout.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(dialogAbout)
        self.buttonBox.setGeometry(QtCore.QRect(240, 300, 81, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(dialogAbout)
        self.label.setGeometry(QtCore.QRect(90, 180, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(dialogAbout)
        self.label_2.setGeometry(QtCore.QRect(90, 230, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(dialogAbout)
        self.label_3.setGeometry(QtCore.QRect(200, 40, 171, 131))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/newPrefix/logo.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(dialogAbout)
        self.buttonBox.accepted.connect(dialogAbout.accept)
        self.buttonBox.rejected.connect(dialogAbout.reject)
        QtCore.QMetaObject.connectSlotsByName(dialogAbout)

    def retranslateUi(self, dialogAbout):
        _translate = QtCore.QCoreApplication.translate
        dialogAbout.setWindowTitle(_translate("dialogAbout", "Dialog"))
        self.label.setText(_translate("dialogAbout", "Versión del programa: 0.0.1"))
        self.label_2.setText(_translate("dialogAbout", "Rubén Blanco Lage"))
import logo_rc
