# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventanaborrar.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogBorrar(object):
    def setupUi(self, DialogBorrar):
        DialogBorrar.setObjectName("DialogBorrar")
        DialogBorrar.resize(522, 203)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogBorrar.sizePolicy().hasHeightForWidth())
        DialogBorrar.setSizePolicy(sizePolicy)
        DialogBorrar.setMinimumSize(QtCore.QSize(522, 203))
        DialogBorrar.setMaximumSize(QtCore.QSize(522, 203))
        self.btnBoxBorrar = QtWidgets.QDialogButtonBox(DialogBorrar)
        self.btnBoxBorrar.setGeometry(QtCore.QRect(90, 130, 341, 32))
        self.btnBoxBorrar.setOrientation(QtCore.Qt.Horizontal)
        self.btnBoxBorrar.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.btnBoxBorrar.setCenterButtons(True)
        self.btnBoxBorrar.setObjectName("btnBoxBorrar")
        self.label = QtWidgets.QLabel(DialogBorrar)
        self.label.setGeometry(QtCore.QRect(160, 50, 221, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(DialogBorrar)
        self.label_2.setGeometry(QtCore.QRect(30, 40, 111, 121))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("img/adios.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(DialogBorrar)
        self.btnBoxBorrar.accepted.connect(DialogBorrar.accept)
        self.btnBoxBorrar.rejected.connect(DialogBorrar.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogBorrar)

    def retranslateUi(self, DialogBorrar):
        _translate = QtCore.QCoreApplication.translate
        DialogBorrar.setWindowTitle(_translate("DialogBorrar", "Dialog"))
        self.label.setText(_translate("DialogBorrar", "¿Seguro que quiere borrar al usuario?"))
